# mehrere Quadrate

import turtle

tina = turtle.Turtle(shape='turtle')
scr = turtle.Screen()
scr.bgcolor("white")

tina.pensize(5)

# Quadrat 1
tina.right(45)
tina.pencolor("red")
tina.fillcolor("cyan")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

# Quadrat 2
tina.right(60)
tina.pencolor("green")
tina.fillcolor("magenta")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

# Quadrat 3
tina.right(60)
tina.pencolor("blue")
tina.fillcolor("yellow")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

# Quadrat 4
tina.right(60)
tina.pencolor("red")
tina.fillcolor("cyan")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

# Quadrat 5
tina.right(60)
tina.pencolor("green")
tina.fillcolor("magenta")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

# Quadrat 6
tina.right(60)
tina.pencolor("blue")
tina.fillcolor("yellow")
tina.begin_fill()
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.forward(100)
tina.left(90)
tina.end_fill()

scr.exitonclick()