import turtle

tina = turtle.Turtle(shape = "turtle")
#turtle.tracer(False)

tina.left(90)

tina.penup()
tina.back(25)
tina.right(90)
tina.back(60)
tina.pendown()

# Wand
tina.pensize(3)
tina.forward(120)
tina.right(90)
tina.forward(70)
tina.right(90)
tina.forward(120)
tina.right(90)
tina.forward(70)
tina.right(90)

tina.penup()
tina.back(15)
tina.pendown()

# Dach
tina.pensize(5)
tina.pencolor("darkred")
tina.fillcolor("red")
tina.begin_fill()
tina.forward(150)
tina.left(120)
tina.forward(150)
tina.left(120)
tina.forward(150)
tina.left(120)
tina.end_fill()

# Fenster
tina.penup()
tina.forward(25)
tina.right(90)
tina.forward(10)
tina.pensize(1)
tina.pencolor("black")
tina.fillcolor("yellow")
tina.pendown()
tina.begin_fill()
tina.forward(40)
tina.left(90)
tina.forward(40)
tina.left(90)
tina.forward(40)
tina.left(90)
tina.forward(40)
tina.left(90)
tina.end_fill()

# Türe
tina.penup()
tina.left(90)
tina.forward(60)
tina.right(90)
tina.pendown()
tina.fillcolor("brown")
tina.begin_fill()
tina.forward(60)
tina.left(90)
tina.forward(40)
tina.left(90)
tina.forward(60)
tina.left(90)
tina.forward(40)
tina.left(90)
tina.end_fill()

turtle.Screen().exitonclick()